In [35]:
import numpy as np
 
class Perceptron(object):
    """Implements a perceptron network"""
    def __init__(self, input_size, lr=1, epochs=10):
        self.W = np.zeros(input_size+1)
        # add one for bias
        self.epochs = epochs
        self.lr = lr
    def activation_fn(self, x):
        return 1 if x >= 0 else 0
    def predict(self, x):
        x = np.insert(x, 0, 1)
        z = self.W.T.dot(x)
        a = self.activation_fn(z)
        return a
    def fit(self, X, d):
        for _ in range(self.epochs):
            for i in range(d.shape[0]):
                y = self.predict(X[i])
                e = d[i] - y
                self.W = self.W + self.lr * e * np.insert(X[i], 0, 1)

In [36]:
mp = Perceptron(5)

In [37]:
mp.W

array([0., 0., 0., 0., 0., 0.])

In [38]:
mp.activation_fn(10)

1

In [39]:
mp.activation_fn(-10)

0

In [40]:
x = np.asarray([-10,-2,-3,4,-50])

In [41]:
x

array([-10,  -2,  -3,   4, -50])

In [42]:
mp.predict(x)

1

In [44]:
X = np.array([
        [0, 0],
        [0, 1],
        [1, 0],
        [1, 1]
    ])
d = np.array([0, 0, 0, 1])
 
perceptron = Perceptron(input_size=2)
perceptron.fit(X, d)
print(perceptron.W)

[-3.  2.  1.]


# 1-)Perceptron class tanımınında var olan fonksiyonları kısaca tanıtınız.

# def __init__(self, input_size, lr=1, epochs=10) : Input Boyutunu alarak Veriler için W yani ağırlığı oluşturan bir constructordir.

# def activation_fn(self, x) : Aktivasyon Fonksiyonu kendisine verilen değer 1'den büyükse 1 döndürür 1'den küçük ise 0 döndürür.

# def predict(self, x): 

# Transpoze dot çarpımı ile tekil değer üretir ve aktivasyon fonksiyonuna gönderir.



# def fit(self, X, d): 

# Verilerin eğitildiği ve oluşturulduğu fonksiyondur. Predict yardımı ile error değerine bakılır.



# 2-)XOR için verileri değiştirip çalışmasınızı gözlemleyiniz.

# X = np.array([[0, 0],[0, 1],[1, 0],[1, 1]])

# d = np.array([0, 1, 1, 0])
 

# perceptron = Perceptron(input_size=2)
# perceptron.fit(X, d)




# 3-)Bu class ile dersimize kayıtlı 40 öğrenci için imza tanıması yapılırsa X ve d değerlerini ne olur, predict fonksiyonu nasıl kullanılır açıklayınız.

# X -> 40 öğrencinin imzalarının 2 boyutlu bir diziye(0 ve 1) dönüştürülmüş data seti olur.
# d-> Her bir öğrencinin imzalarının tutulduğu 40x40 lık 2 boyutlu bir dizi olur.





# 4-)Bu modelin hatası nasıl elde edilir, kendi çözümünüzü/ yorumunuzu yazınız.

# Bu modelin hatası XOR kapısı ile elde edilir. XOR girdileri tekil olarak ayrılamazdır. Bunun çözümü çoklu perceptron kullanımıdır.
